### ISSUE TITLE
Add option for each way to keep matching the search expression in a file and action each found

### ISSUE THREAD

**Issue by dlmiles** [bomsy/grunt-regex-replace#11]
Add option for each way to keep matching the search expression in a file and action each found.

Maybe I am overlooking some usage that will replace all matches in a file, including multiple matches on a single line.

But it seems to only replace the first match, then reset the file back to start,

**Comment by minto4644** [comment]
Have you solved the issue? Or is it still open. 

Doesn't global option 'g' replaces all matches ?

**Comment by dlmiles** [comment]
No only the first match is found and processed.

Make a unittest to confirm it ?

**Comment by bomsy** [comment]
Can you give an example pls?

**Comment by dlmiles** [comment]
Just responding to this query as I just noticed it up for attention.  I don't have the original usage to hand, but will try to dig out the details but I do remember the situation.

Make a *.html file with multiple "<link ....>" tags inside the <head>.
Now setup a search replace to replace the "<link ...>" form with the "<link ..../>" form, both are valid in all HTML document (but people prefer shorted files so HTML compressors may remove it), but only the "/>" close is valid for XHTML files.
I found it was not possible to do this global search and replace across the whole file.

If you think it should work (as you have more knowledge of use cases of this plugin than I), maybe you can jot an example few lines of how you expect it to work.

What I found was that it restarted the matching process from the beginning of the file, and simply replaced the first occurrence (and stopped).

I will try to write up a unit test showing this based on the original project (I need to dig out for you).

**Comment by bomsy** [comment]
A unit would be perfect.

**Comment by k-funk** [comment]
I had this same problem. Turns out it's because I didn't understand [`new RegExp()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp). I was using `search: /(<pre><code\ class=".*?">)([\S\s]*?)(<\/code><\/pre>)/,` with `flags: 'g'`, which doesn't work as I expected it to. `RegExp` can take EITHER a regex, or a string-regex with flags as the second argument, but not a regex with flags. I think this library should either figure this out for the user, or throw an error when flags are passed, but will not be used.

I switched to `search: /(<pre><code\ class=".*?">)([\S\s]*?)(<\/code><\/pre>)/g,` with no flags to make it work as expected.

**Comment by bomsy** [comment]
Thanks @k-funk for the clarification. So basically if a `RegExp` object is passed to the `search` property, we just take the already created object and run with that, in that case there is no need for the use of the `flags` property. I think a clarification in the docs (which @k-funk has done) is all that is need for this, trying to implement this would lead to doing alot of ugly things in the code.
