### ISSUE TITLE
Isn't \s recognized?

### ISSUE THREAD

**Issue by qcgm1978** [bomsy/grunt-regex-replace#6]
Hello:
My example:the test to be replaced
```
#version           2013-10-14
```
The following works:
```
replaceManifestVer: {
                src: ['<%= pkg.targetFolder %>/<%= pkg.help_release %>/help.manifest'],
                actions: [
                    {
                        name: 'update manifest ver',
                        search: '#version.+\-',
                        replace: '',
                        flags: 'g'
                    }
                ]
            }
```
The txt will leave '14', but the following doesn't work.
```
{
                        name: 'update manifest ver',
                        search: '#version\s+\-',
                        replace: '',
                        flags: 'g'
                    }
```
So \s can't be recognized. Why?

**Comment by dlmiles** [comment]
Did you try:

```
search: '#version\\s+\-',
```

As it maybe eaten due to JavaScript strings also using similar sequences like '\n' and '\r', is it defined in the JS language specification what happens when the character after it is unknown.

Sorry for the w3schools link http://www.w3schools.com/js/js_strings.asp but it is stop google hit with relevance.
